development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:b7f7bf94d71be7004312bf6175a059fb@soapfish.redistogo.com:10146/ #<%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: classifier_production
